# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a9c6edb7f48f1c3e753caefb101b03b4aa6bfe5a3206bd2514b486cae1b86451b44e2d951fd6fd4e894359be55b4440e4dd699b23da79b13b837cbe41b62f74

test:
  secret_key_base: e9ec2d218f9cacdae793135dcc6989926bf120b879c903150c28678626e2ffa2e9181c38a5a5726ac7d6e7f3cb293776c89ebafc2d0d1627e4bcc7e76f10a3ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
